### ISSUE TITLE
Use RcppParallel to improve speed.

### ISSUE THREAD

**Issue by dewittpe** [dewittpe/pccc#10]
Set up the C++ code to use RcppParallel to work on a subject.

Currently, the C++ is designed for one subject.  A `Map` call in the `ccc` function sends each subject's data to the `ccc_rcpp` call.  Redesign so that the each subject is set up to go to its own core.

**Comment by tdbennett** [comment]
Sounds reasonable, but can you please expand on the reason this is needed?

**Comment by dewittpe** [comment]
R, and the `pccc` package as a result, are single threaded.  There is no reason why the `ccc` function can't use more than one computation core.  One option would be to let the end user program their own multi-threaded approach to using the `ccc` function.  However, the end user options are generally not OS independent.

I would like to build the multi-threaded approach via RcppParallel so that the multi-threading would be done at a compiled code level and would work on Windows, OSX, Linux, and Solaris.  I plan to have an option in the API so users can specify the number of cores to use.

**Comment by dewittpe** [comment]
It is worth noting that while I was working on this issue I was able to improve the speed of the `ccc` call.  See commit 29b5ab080eb82c7e66b7a3a0dde34d1eab34b27a on the `dev`elopment branch.  I'll likely merge that into `master` if the parallel computing code doesn't fall into place soon.

**Comment by dewittpe** [comment]
This more work than is needed.  Better to leave a fast single thread process and let end users break up the job on their own.
