### ISSUE TITLE
add Jamie to repo

### ISSUE THREAD

**Issue by tdbennett** [dewittpe/pccc#5]
Hi @dewittpe, can you please add @jamesfeinstein to the repo?

**Comment by dewittpe** [comment]
Are you requesting that @tdbennett, @jamesfeinstein have push access?

**Comment by tdbennett** [comment]
Good question. Maybe just notifications? I was extrapolating from our bitbucket experience.

**Comment by dewittpe** [comment]
I can't force notifications for a user/  He'll have to start watching this repo to get the updates, emails, etc.
