### ISSUE TITLE
ICD code pre-processing

### ISSUE THREAD

**Issue by tdbennett** [dewittpe/pccc#9]
@dewittpe to explore `icd` R package capabilities vs. Stata native `icd clean` functions. 

SAS and Stata code in 2014 paper differ in this: Stata script includes pre-processing that removes leading and trailing blanks and leading 0's.

**Comment by dewittpe** [comment]
I've started to explore the [`icd`](https://cran.r-project.org/package=icd).  I've looked at the ICD codes used in the original SAS and STATA files and compared to the codes which are documented in the `icd` package.  It appears that the ICD9 are well defined, but there are issues with the longer ICD10 codes.  See the files in this [gist](https://gist.github.com/dewittpe/c12a40504d391b2881996e123410b2e9).

**Comment by dewittpe** [comment]
Looking at http://www.icd10data.com/ICD10CM/Revised_Codes/2017, I get the felling that the `icd` package isn't yet completely icd10 ready.

**Comment by dewittpe** [comment]
My 2-cents on this general issue:  

I think it would be nice to build a data set of the following form:

|icdv|diag|classification|short|decimal|definition|
|:--:|:--:|:------------:|----:|------:|:---------|
|9   |dx  |neuromusc     | 3180|318.0  |Moderate intellectual disabilities|
|9   |dx  |neuromusc     | 3181|318.1  |Severe intellectual disabilities  |
|... |... | ....         | ... | ...   | ... |
|9   |pc  |neuromusc     | 0152|015.2  |Unspecified non-arthropod-borne viral diseases of central nervous system|
|... |... | ...          | ... | ....  | ... |


The short and decimal codes will be character strings.

We can start by having this table and guide lines for users.  Some of the functions from the `icd`  package *might* help.

**Comment by dewittpe** [comment]
Oh, and the codes are not unique to a CCC classification...

**Comment by tdbennett** [comment]
Currently requiring strings to have leading zeroes, not have periods. Users can choose how they want to do that.
